algoritmo "ex04"

var
   contador, contador2 : inteiro
inicio
      contador <- 1
      contador2 <- 1
      enquanto (contador < 21) faca
               escreval(contador)
               contador <- contador + 1
      fimenquanto
      
      escreval("")
      
      enquanto (contador2 < 21) faca
               escreva(contador2)
               contador2 <- contador2 + 1
      fimenquanto

fimalgoritmo
