algoritmo "11042022ex012"

var
   height, pesoIdeal : real
inicio
escreval("informe sua altura para calcular-mos seu peso ideal :")
leia(height)
pesoIdeal <- (72.7 * height) - 58
escreval("")
escreval("")
escreval("o seu peso ideal é :", pesoIdeal, "Kg")




//Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal, usando a seguinte fórmula: (72.7*altura) - 58
fimalgoritmo
